### ISSUE TITLE
New styles for different types of text in docs

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs-sphinx-theme#24]
@isabela-pf will help us decide on different styles for:
- Shortcuts
- Guilabels
- Links
- Text in monospaced font (code)
- Bold for emphasis

**Comment by isabela-pf** [comment]
Part of this also became consolidating and creating a united color palette for the website. Here's a list of the colors I'm proposing right now:
<img width="399" alt="Palette Post" src="https://user-images.githubusercontent.com/50221806/90716952-0f075580-e263-11ea-8a43-1997be38317c.png">

Colors that currently are not on the website are marked "new." From top to bottom, they are `#d50000` (new), `#8c0000` (new), `#1c4489`, `#212121` (new), `#4e4e4e` or `rgb(78, 78, 78)` as it currently is in the docs, `#ededed` (new), and `#fffff`.

Below I've listed a set of proposed text styles for the website with examples and listed styles for ease of reference.

## Basic/Body text
<img width="330" alt="Body" src="https://user-images.githubusercontent.com/50221806/90717011-3f4ef400-e263-11ea-914b-f30b31e00127.png">

`#212121` Raleway/Sans Serif 

## Emphasis
<img width="330" alt="Emphasis" src="https://user-images.githubusercontent.com/50221806/90717052-6e656580-e263-11ea-957f-08bd629c0ae1.png">

`#212121` Raleway/Sans Serif Semibold

## Links
<img width="330" alt="Links" src="https://user-images.githubusercontent.com/50221806/90717102-91901500-e263-11ea-9291-f397f416097a.png">

`#d50000` Raleway/Sans Serif 

## Shortcuts
<img width="330" alt="Shortcuts" src="https://user-images.githubusercontent.com/50221806/90717158-c69c6780-e263-11ea-81a6-b13577dd58a7.png">

`#212121` Menlo/Monospace with `#ededed` background

## Monospaced (inline code, mostly)
There are two options. Both use Menlo/Monospace fonts.
<img width="330" alt="Monospace Inline 2" src="https://user-images.githubusercontent.com/50221806/90717349-3ad70b00-e264-11ea-93bf-a9c7cc1126c9.png">

^ First is to keep the color as the pink `#e83e8c`.

<img width="330" alt="Monospace Inline" src="https://user-images.githubusercontent.com/50221806/90717450-7b368900-e264-11ea-8951-949bbea31383.png">

^ Or change it to `#8c0000`. I prefer this option since I think it fits better with the overall color palette and easier to read.

## UI Labels
I also have two ideas for UI Labels. Both use Raleway/Sans Serif. 
<img width="330" alt="UI Labels 2" src="https://user-images.githubusercontent.com/50221806/90718010-cbfab180-e265-11ea-931a-ebd6baf43fd2.png">

^ `#ffffff` text and `#1c4489` background. Since there was a desire to make it look closer to default Spyder UI, maybe the dark with the light text is the right way to go. I don't think the team liked this as much, so we also have the next option.

<img width="330" alt="UI Labels 1" src="https://user-images.githubusercontent.com/50221806/90718019-cf8e3880-e265-11ea-9ccd-5d39086b7cd9.png">

^ `#1c4489` text and `#ededed` background. Still looks closer to UI than code and has that little bit of blue to reference Spyder.

**Comment by juanis2112** [comment]
For inline code we will be using the pink option but with https://fonts.google.com/specimen/Inconsolata?category=Monospace because Menlo is not available in Google fonts.
For UI labels we will be using the second option.
