### ISSUE TITLE
New design for open collective button

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs-sphinx-theme#25]
After our meeting we decided to change our open collective button to match the squared style icons we have in our page. @isabela-pf can you post your ideas on this issue?

**Comment by isabela-pf** [comment]
Button styling is designed to match this button already on the docs:
![Open Chat Button](https://user-images.githubusercontent.com/50221806/90713540-6654f800-e25a-11ea-8835-1aafe1577c3c.png)

I was originally working with `#8c0000` as the new red (from the [logo redesign](https://github.com/spyder-ide/spyder/issues/13181)), but it doesn't mesh well with the dark grey `rgb(78, 78, 78)` being used elsewhere on the website. Here's a screen shot of me testing it out:

<img width="1010" alt="Screen Shot 2020-08-19 at 8 12 24 PM" src="https://user-images.githubusercontent.com/50221806/90712928-fc881e80-e258-11ea-964f-bf0f115b05a9.png">

Instead I found a different, brighter red that still meets accessibility standards for use with white text. This is `#d50000`. I also plan to work with this elsewhere on the website (like over in #24 as I try to set a color palette) and can try it with the logo for the next iteration since it works a lot better with the grey. Here's what `#d50000` looks like on the grey in the footer:

<img width="1006" alt="Screen Shot 2020-08-19 at 8 18 23 PM" src="https://user-images.githubusercontent.com/50221806/90713281-d616b300-e259-11ea-893a-45ae121af6f2.png">

Since GitHub doesn't support SVGs in comments, here's a [link to the SVG](https://drive.google.com/file/d/1nHqdqcSGZzVfQy4WnDaZ4jJPxsbR-_uZ/view?usp=sharing).

**Comment by ccordoba12** [comment]
@juanis2112, I think this is solved now, right?

**Comment by juanis2112** [comment]
Yes. Closing it now.
